displayName=Loot Inside
author=bop
description=Stops you from leaving the Theatre of Blood without looting your chest
tags=loot,theatre of blood,tob,pvm,bingo
plugins=com.bop.LootInsidePlugin
build=standard
